# Generated by Django 5.0.2 on 2024-02-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='j'),
            preserve_default=False,
        ),
    ]
